### ISSUE TITLE
Use PeculiarVentures/webcrypto instead | also?

### ISSUE THREAD

**Issue by tomByrer** [dollarshaveclub/cloudworker#102]
We Windows users sometimes have issues with `node-gyp` which [PeculiarVentures/node-webcrypto-ossl](https://github.com/PeculiarVentures/node-webcrypto-ossl/issues/150) uses to build/`install`.  They do have a another repo that is API comparable save a few algorithms that do not overlap between [OSSL C++](https://github.com/PeculiarVentures/node-webcrypto-ossl#supported-algorithms) & [WebCrypto](https://github.com/PeculiarVentures/webcrypto#supported-algorithms).

Also, seems that CloudFlare Workers use [only WebCrypto API](https://developers.cloudflare.com/workers/reference/#standard-apis) anyhow.  Does it make sense to switch over to PeculiarVentures' WebCrypto for Node for (hopefully) faster & less bug-prone installs?  Or is there another reason you prefer C++, like runtime performance?  Or have the option for both?

Thanks for your project & consideration!

**Comment by hankjacobs** [comment]
I'm all for switching to `@peculiar/webcrypto`. @ssttevee took a shot at it in #81 but [we ran into an issue](https://github.com/dollarshaveclub/cloudworker/pull/81#issuecomment-485292676) with the way cloudworker is architected that was a show stopper. Feel free to take a stab at it if you'd like!
