### ISSUE TITLE
Question: How can I pass in metadata?

### ISSUE THREAD

**Issue by SamJarmanPP** [dollarshaveclub/cloudworker#103]
We have a `manifest.json` for metadata which we fill with secrets and what not for bindings. I dont see a CLI option to specify this? How can I achieve this?

Thanks!

**Comment by hankjacobs** [comment]
Hi @SamJarmanPP! Is the `manifest.json` a Cloudflare Worker concept? If so, could you please link to the documentation? Thanks!

**Comment by SamJarmanPP** [comment]
Sure, something like this https://developers.cloudflare.com/ssl/ssl-for-saas/hostname-specific/custom-metadata/ @hankjacobs 

Cheers!

**Comment by hankjacobs** [comment]
Oh neat! I didn't know that was a feature. Currently, cloudworker doesn't support it but I wouldn't be opposed to adding it as a feature. Off the cuff, a flag could be added that allows one to specify the path (or maybe the actual JSON) to a file that contains the JSON blog to inject with every request that is handled by the worker. No guarantees on when I can get to that but PRs are always welcome!

**Comment by SamJarmanPP** [comment]
Yeah! I was thinking a CLI arg like the key/value pairs currently there. Cheers!

**Comment by boulter** [comment]
How about allowing just passing it in on the request as additional request object params? It currently looks like [it's always overridden](https://github.com/dollarshaveclub/cloudworker/blob/5b3ae4e5f895134a40511cbcab3dbd2ac6d67ceb/lib/runtime/fetch.js#L78-L90).

I'd like to be able to do something like 
```
new Cloudworker.Request('http://foo.com/test/', {
  cf: { hostMetadata: { myMetadataValue: true } },
});
```
