### ISSUE TITLE
cloudworker does not support export / require?

### ISSUE THREAD

**Issue by andreasmauer** [dollarshaveclub/cloudworker#110]
I have a worker already running in cloudflare and working fine. When I try to test it with cloudworker though I always get the following error: ReferenceError: require is not defined

Do cloudworker support export/requires?

**Comment by hankjacobs** [comment]
Neither Cloudflare Workers nor cloudwork does. Check out https://developers.cloudflare.com/workers/writing-workers/using-npm-modules/ for how to use modules. The TLDR is use webpack to combine the modules with your script and then use cloudworker to run the resulting script.

**Comment by hankjacobs** [comment]
This thread has an approach too: https://github.com/dollarshaveclub/cloudworker/issues/95
