### ISSUE TITLE
Missing runtime bindings: Timers

### ISSUE THREAD

**Issue by tysonclugg** [dollarshaveclub/cloudworker#120]
As per https://developers.cloudflare.com/workers/reference/apis/standard/, the timer API (`setInterval`, `clearInterval`, `setTimeout`, and `clearTimeout`) should be available in the request context.

**Comment by coreybutler** [comment]
Pretty sure these are available: https://github.com/dollarshaveclub/cloudworker/blob/master/lib/runtime.js#L11-L14
