### ISSUE TITLE
Isolates

### ISSUE THREAD

**Issue by Immortalin** [dollarshaveclub/cloudworker#129]
Can isolates be added? I.e. untrusted code sandboxing

**Comment by iameli** [comment]
Curious about your use case here. You could just run multiple cloudworker instances to isolate scripts from each other... but I don't really think this project was designed to provide comprehensive production-grade isolation to the backing Node.js environment. (But that'd be cool!)

**Comment by tmikaeld** [comment]
See https://github.com/dollarshaveclub/cloudworker/issues/93
