### ISSUE TITLE
[Feature Request] Add support for HTMLRewriter

### ISSUE THREAD

**Issue by Cherry** [dollarshaveclub/cloudworker#138]
Testing `HTMLRewriter` locally would be really awesome. Currently, `ReferenceError: HTMLRewriter is not defined` is just thrown when attempting to use it.

Reference: https://developers.cloudflare.com/workers/reference/apis/html-rewriter/
Cloudflare do publish the source for this too, at https://github.com/cloudflare/lol-html

**Comment by bkeroackdsc** [comment]
Hi @Cherry! Unfortunately cloudworker is no longer actively maintained at DSC, so this is unlikely to be looked at in the near future. Perhaps we will find a volunteer at some point.

**Comment by xtuc** [comment]
The HTMLRewriter could be integrated using https://github.com/cloudflare/lol-html/issues/38

**Comment by grakic** [comment]
Thanks to [@defjosiah](https://github.com/cloudflare/wrangler/issues/1047#issuecomment-610074742) I have a bit more complete HTMLRewriter shim: https://gist.github.com/grakic/b25d54f27223154023cfb3042ab66d41

Use locally with webpack.dev.js as:
```
    plugins: [
        new webpack.ProvidePlugin({
            HTMLRewriter: [__dirname + '/src/mock.js', 'default']
        }),
    ]
```

There are differences like in how it handles `<div>Hello<p>World</p>Extra<br></div>` but it is similar enough that it helped me debug a few issues locally.

**Comment by defjosiah** [comment]
@grakic that looks great! Thanks for extending it. Will replace our mock with that 😄

**Comment by Cherry** [comment]
I'm going to go ahead and close this. Cloudflare's `wrangler dev` has taken over all of our dev use-cases and needs.

**Comment by qwtel** [comment]
In case someone's still looking for a HTMLRewriter polyfill, here is another one: https://github.com/worker-tools/parsed-html-rewriter
