### ISSUE TITLE
Active Maintenance of Cloudworker?

### ISSUE THREAD

**Issue by AngusMorton** [dollarshaveclub/cloudworker#144]
In the README, it says Dollar Shave Club is no longer _actively_ maintaining Cloudworker, what does that mean? 
* Are you still going to be merging PR's/reviewing issues until a new owner is found?
* Has Dollar Shave Club decided to move away from Cloudflare Workers? If so, I'd love to know why.

**Comment by bkeroackdsc** [comment]
The person who was the primary maintainer of cloudworker no longer can do so. We have a few people who are contributing time here and there but it will be best-effort. The README tries to make this clear to anyone who opens an issue or bug.

**Comment by aleclarson** [comment]
Cloudflare's `wrangler` CLI has a `dev` command that supplants the need for `cloudworker`.

See here: https://github.com/cloudflare/wrangler#-dev

**Comment by xtuc** [comment]
@aleclarson it's a great solution but doesn't work offline and it's not pratical to me in unit test/CI.

**Comment by aleclarson** [comment]
> doesn't work offline

You sure about that? The docs say it starts a localhost server. Why wouldn't that work offline?
