### ISSUE TITLE
Livepeer volunteering to maintain

### ISSUE THREAD

**Issue by iameli** [dollarshaveclub/cloudworker#145]
> ⚠️ Cloudworker is no longer actively maintained at Dollar Shave Club. If you're interested in volunteering to help, please open an issue ⚠️

I'm interesting in volunteering to help! Livepeer is developing an API that's targeted primarily at Cloudflare Workers; having a local dev environment for such a thing is important. I'd be happy to take on maintainership.

First order of business would be getting a `KV.list()` implementation merged: https://github.com/dollarshaveclub/cloudworker/issues/130

Happy to discuss further, email is eli@livepeer.org.

**Comment by bkeroackdsc** [comment]
Thanks @iameli . I'll send you an email and we can discuss details.

**Comment by qmhoang** [comment]
@iameli what happen to this?  Did Livepeer no longer wanting to maintain this?

**Comment by iameli** [comment]
@qmhoang Nope, still interested! Sorry, ball's in my court: @bkeroackdsc told me to ping him when I had stuff ready for review and I hadn't quite gotten to it yet. I should have some time to spend in the next couple of days.

Is there a particular bug fix or feature you'd been hoping to get merged, @qmhoang?

**Comment by qmhoang** [comment]
@iameli I was hoping for either #122 or #130 to get merged.  We're using Workers and Workers KV heavily at Optimizely and I was hoping for a library that could be used for local dev (as well as local e2e testing).
