### ISSUE TITLE
Read protocol off of headers

### ISSUE THREAD

**Issue by kamal** [dollarshaveclub/cloudworker#26]
I'm spiking replacing `sw-test-env` with `cloudworker` in our cloudflare worker test setup. We typically use cloudflare workers as a rewriting proxy fronting different URL endpoints, so we usually build very narrow handlers that check that the hostname, path, scheme, port and content type are what we expect, otherwise we let the request pass through unmodified.

For reference, here is a typical way of firing a fetch event with `sw-test-env`:

```javascript
const request = new Request('https://app.envoy.com/a/auth/v0/token', {
  method: 'POST',
  headers: { 'Content-Type': 'application/json' },
  body: JSON.stringify({ grant_type: 'refresh_token', scope: 'token.refresh' })
})

const response = await sw.trigger('fetch', request)
```

with Cloudworker, I had to change it to look like below: 

```javascript
const server = new Cloudworker(script).listen(3333);
const response = await axios('http://localhost:3333/a/auth/v0/token', {
  method: 'POST',
  headers: {
    'Content-Type': 'application/json',
    Host: 'app.envoy.com',
    'X-Forwarded-Proto': 'https'
  },
  body: JSON.stringify({ grant_type: 'refresh_token', scope: 'token.refresh' })
});

assert ...
await server.close();
```

I could not find a way to convince Cloudworker to use `https` to construct the `fetch` event. Is this a known limitation?

**Comment by hankjacobs** [comment]
I think the feature I just added should support your use-case. I've [released a beta](https://github.com/dollarshaveclub/cloudworker/releases/tag/v0.0.8-beta.3) that includes it. The README touches on [how to use it](https://github.com/dollarshaveclub/cloudworker#package-usage). Let me know what you think.
