### ISSUE TITLE
Empty Transfer-Encoding header included on fetch requests causes problems

### ISSUE THREAD

**Issue by hankjacobs** [dollarshaveclub/cloudworker#33]
Originally appeared [here](https://github.com/dollarshaveclub/cloudworker/issues/25#issuecomment-449564734).
>  Hi there,
> 
> Thanks for the quick response.  I tried it will the following:
> 
> ```
> addEventListener("fetch", event => {
>   event.respondWith(fetchAndStream(event.request))
> })
> 
> async function fetchAndStream(request) {
>   // Fetch from origin server.
>   let response = await fetch("http://www.google.com/robots.txt")
> 
>   // Create an identity TransformStream (a.k.a. a pipe).
>   // The readable side will become our new response body.
>   let { readable, writable } = new TransformStream()
> 
>   // Start pumping the body. NOTE: No await!
>   streamBody(response.body, writable)
> 
>   // ... and deliver our Response while that's running.
>   return new Response(readable, response)
> }
> 
> async function streamBody(readable, writable) {
>   let reader = readable.getReader()
>   let writer = writable.getWriter()
> 
>   while (true) {
>     const { done, value } = await reader.read()
>     if (done) break
>     // Optionally transform value's bytes here.
>     await writer.write(value)
>   }
> 
>   await writer.close()
> }
> ```
> 
> Unfortunately the following line is adding the header a blank `transfer-encoding` header, which results in a 400 response from google, and other upstream sources I've tried.
> 
> https://github.com/dollarshaveclub/cloudworker/blob/master/lib/runtime/fetch.js#L15
> 
> Removing this line get things working.

> Here's an example from an ngrep of the previous robots.txt fetch from google (the worker above).
>   
> The transfer-encoding is being set to an empty string, with google this is returning a 400.  With S3 this is returning a 501 not implemented.
> 
> ```
> interface: en0 (192.168.0.0/255.255.255.0)
> filter: (ip) and ( port 80 )
> 
> T 192.168.0.10:53875 -> 216.58.213.100:80 [AP]
> GET /robots.txt HTTP/1.1.
> transfer-encoding: .
> Accept: */*.
> User-Agent: node-fetch/1.0 (+https://github.com/bitinn/node-fetch).
> Accept-Encoding: gzip,deflate.
> Connection: close.
> Host: www.google.com.
> .
> 
> 
> T 216.58.213.100:80 -> 192.168.0.10:53875 [AP]
> HTTP/1.0 400 Bad Request.
> Content-Length: 54.
> Content-Type: text/html; charset=UTF-8.
> Date: Sat, 22 Dec 2018 11:05:26 GMT.
> ```
> 
> 
> The files we are streaming from S3 (we are doing GETs, not POSTs) via the worker vary from 1mb to 300mb.  Unfortunately, I can't share the worker we have (the intellectual proper is that of work, so I can't provide the code verbatim).
> 
> There's an example worker that is using the byob reader, and chunking on, which will hopefully demo it: https://github.com/dollarshaveclub/cloudworker/issues/32.
> 
> What we are doing is loading in chunks of the file, whilst filtering the contents, before the file is sent to the user.  We only need to filter certain sections of the files, so once we've filter the correct part of the file, we can send the rest to the user unmodified.
> 
> The use reading the source in chucks comes from this cloudflare ticket, to reduce the CPU used by the worker.:
> 
> - https://community.cloudflare.com/t/worker-and-streaming-json/26509/8

**Comment by larkin-nz** [comment]
Hey @hankjacobs 

I'm getting a 501 when making a fetch request to any URL (with any method).

I had this the other day but after reinstalling the package it had fixed itself, any idea what's going on here?

Not quite sure what the bug here is!

**Comment by hankjacobs** [comment]
@larkin-nz Do you have some example requests that reproduce this?

**Comment by hankjacobs** [comment]
Regarding setting `transfer-encoding` to an empty string when fetch'ing with a body:
The intention with that is to disable chunked transfer-encoding. When the body of a request is a Stream (node or a browser), node.js will automatically set the transfer-encoding to chunked. For the most part that was ok except that any request that gets cloned has a body of type ReadableStream even if the original body was created from string or something. This was causing problems for us here at DSC because some upstream services don't support chunked transfer-encoding. This was a solve (an admittedly hacky one at that) for this problem. I guess I'll have to reevaluate this approach. Now that we're using a forked version of node-fetch, I think the real solution will be to propagate the original body type across calls to clone().

I'm also open to suggestions

**Comment by larkin-nz** [comment]
@hankjacobs - making any request to a service (such as Stripe) with POST seems to throw a 501 for me.

What if we set 'transfer-encoding' to 'identity' instead? As far as I understand this is the default in most systems and is supported by everything.

**Comment by hankjacobs** [comment]
Sorry for the delay in response. It's been a bit crazy the past few days (and still going). I think the proper solution is not to touch the `transfer-encoding` header at all. I'm leaning towards reading the entire request body in the fetch shim prior to calling the real fetch. This most closely matches what actually happens in Cloudflare with the minor difference being that the fetch request body is fully read out of process but prior to sending upstream -- you can't actually send a chunked request body as far as I can tell. That behavior can be disabled by Cloudflare but is on by default.

**Comment by larkin-nz** [comment]
No worries at all!

That sounds fine to me - I can't think of a better solution to it than that right now, so I think let's just go with that.

I'll be away for the next four days, but I'd really appreciate it if you've managed to implement it by then if you have the time.

Thanks again!

**Comment by hankjacobs** [comment]
Most recent beta should fix the issue. Please open a new issue if the issue persists. Thanks!
