### ISSUE TITLE
Mock fetch inside worker for tests

### ISSUE THREAD

**Issue by atmin** [dollarshaveclub/cloudworker#41]
First, thank you for this project, it helped convert my node-cloudflare-riddled-with-if-process-env-checks isomorphic JS into more readable codebase.

Scenario: I want to make a bunch of snapshot tests to my worker - I have requests and expected responses. However, my worker makes calls to external services and I want to mock those, probably using `fetch-mock` (alternatives are fine, if you have suggestions). I have a way to accomplish this through polluting my worker code with "am i under test" check and mock accordingly, but instrumenting this from the outside is the clean way.

Currently, Cloudworker does not seem to provide a way to provide a custom `fetch`, it unconditionally loads `node-fetch` Node polyfill in the runtime. What would be a good way to approach this?

**Comment by atmin** [comment]
I'm importing it as a package. Current workaround is to pass `{ bindings: { mockedFetch: fetchMock().sandbox() } }` to `Cloudworker` from the runner script and use what's available in the worker code.

I'm thinking of moving `Object.assign(this, bindings)` at the end of `Context` constructor, so user-provided bindings override the defaults. I'll try this tonight.

**Comment by hankjacobs** [comment]
I think that'll work. I also like that approach as well but I want to give it a little more thought, too. Mind opening a PR with that change if it works? Thanks!

**Comment by atmin** [comment]
Yep, that works. PR: https://github.com/dollarshaveclub/cloudworker/pull/42

**Comment by hankjacobs** [comment]
Thanks! Added to [most recent beta](https://github.com/dollarshaveclub/cloudworker/releases/tag/v0.0.8-beta.8).

**Comment by lasergoat** [comment]
Just a note for future people with this issue:

@atmin's comment had a slight issue: fetchMock is not a function. you should instead do `fetchMock.sandbox()`

**I'm sure this will help someone, so here's mu full unit test for the worker:**

Like they said, do: 

```npm install -g -D @dollarshaveclub/cloudworker@beta```

Then, in your unit tests when including the fetch binding do:

```
/**
 * GUIDE FROM https://developers.cloudflare.com/workers/deploying-workers/unit-testing/
 *
 * This file will test the script called Script1
 */

const fetchMock = require("fetch-mock");
const jwt = require("jsonwebtoken");
const assert = require("assert");

// make a fetch instance for the worker script
// that we can mock our call on also
const ourFetchMock = fetchMock.sandbox();

// jwt helpers
const jwtSecret = "aaa";
const jwtPayload = () => ({
  sub: "1",
  merchant: "2"
});

/**
 * This code will run before each test
 */
const resetTestScenariosBeforeEach = () => {
  const bindings = {
    // we have to declare `require()` within our script
    // and because cloudworker just gets a string of the script
    // it's not aware of it's path, so requiring local files fails
    // so, this ternary is a cheap way to allow node modules to be required and the local files
    // to be adjusted since we are currently in the test directory
    require: path => require(path.startsWith(".") ? `../${path}` : path),

    // by default, most tests will use a spy to fetch
    // if false though, we'll allow the script code to use real fetch,
    // BUT our test will use mockFetch to bypass the real http request
    fetch: ourFetchMock
  };

  Object.assign(
    global,
    new (require("@dollarshaveclub/cloudworker"))(
      require("fs").readFileSync("script-payment-methods.js", "utf8"),
      {
        bindings
      }
    ).context
  );
};

describe("Script1: Test Server Calls", function() {
  this.beforeEach(() => resetTestScenariosBeforeEach(false));
  this.afterEach(() => {
    // clear out the fetch calls between tests
    ourFetchMock.restore();
  });

  it("should handle validation errors", async function() {
    ourFetchMock.post("https://some-api.com/v1/", 422);

    const req = new Request("https://some-service.com", {
      method: "POST",
      body: JSON.stringify({
        prop: "9999"
      }),
      headers: {
        "content-type": "application/json",
        authorization: `Bearer ${jwt.sign(jwtPayload(), jwtSecret)}`
      }
    });

    // we are expecting a JSON object showing some errors
    // in this test 
    const res = await fetchAndApply(req);
    const body = await res.text();
    const json = JSON.parse(body);

    assert(body.includes("Validation Errors"));
    // assert that a key exists in the response
    assert(json.validation);
  });

  // ...
});

```

**Comment by sejoker** [comment]
Thanks @lasergoat  it was really helpful, one note to add, then you want to call fetch using Request object:
```
let req = new worker.Request('https://example.com');
let res = await fetch(req);
```
Additional setup is needed as [per docs](http://www.wheresrhys.co.uk/fetch-mock/#usagecustom-classes):

```
const Cloudworker = require("@dollarshaveclub/cloudworker");
const fmock = require("fetch-mock");
Object.assign(fmock.config, {
    Headers: Cloudworker.Headers,
    Request: Cloudworker.Request,
    Response: Cloudworker.Response
  });

  fetchMock = fmock.sandbox();
```
