### ISSUE TITLE
Implement request.formData() in ShimRequest

### ISSUE THREAD

**Issue by kamal** [dollarshaveclub/cloudworker#46]
In [Cloudflare's documentation](https://developers.cloudflare.com/workers/recipes/post-requests/), they make use of Service Worker's `request.formData()` to be able to get to multipart form data in the request. This is currently uninimplemented in `ShimRequest`.

For reference, to post `FormData` in the request, I am passing an instance of `FormData` as the body, as [documented when using in conjunction with `node-fetch`](https://github.com/form-data/form-data#node-fetch) which I believe is what `Cloudworker.Request` is using.

```javascript
  const body = new FormData()
  body.append('grant_type', 'password')
  body.append('scope', 'token.refresh')

  const request = new Cloudworker.Request(
    'https://app.envoy.com/a/auth/v0/token',
    {
      method: 'POST',
      headers: { 'Content-Type': 'multipart/form-data' },
      body
    }
  )

  const response = await cw.dispatch(request)
```

**Comment by hankjacobs** [comment]
Thanks for the heads up. I’ll look into it.

**Comment by paulbhartzog** [comment]
After getting cloudworker listening on port 3000, I also tried to post formData but I got this response:

`TypeError: request.formData is not a function`

Any plans for implementing formData within cloudworker?

**Comment by hankjacobs** [comment]
Yep, at some point. That being said, PRs are welcome :). To those interested in giving it a shot, the best place to make that change is probably in [our fork of node-fetch](https://github.com/dollarshaveclub/node-fetch).

**Comment by rsanchez** [comment]
Any consideration for this issue? There is an existing PR (https://github.com/dollarshaveclub/node-fetch/pull/5) with an implementation of FormData.

**Comment by hankjacobs** [comment]
Yep, I'm all for it. I need to get my permissions to that repo fixed and then I'll merge it. Thanks!

**Comment by hankjacobs** [comment]
I've merged it. I'm now waiting for some NPM permissions to get sorted and then I can release a new version and use it cloudworkers.

**Comment by kamal** [comment]
@hankjacobs did you manage to sort out the npm permissions?

**Comment by hankjacobs** [comment]
Still working on it but I was able to get node-fetch published. I’ll work on getting a new version of cloudworker published sometime this week

**Comment by hankjacobs** [comment]
A beta [has been published](https://github.com/dollarshaveclub/cloudworker/releases/tag/v0.1.0-beta.3). Prod version will be deployed in the next week or so pending any bugs being reported.

**Comment by hankjacobs** [comment]
Relevant PR #96
