### ISSUE TITLE
Request object does not include .cf object.

### ISSUE THREAD

**Issue by jbeeko** [dollarshaveclub/cloudworker#56]
The event.request  object provided does not include the .cf attribute as described here https://developers.cloudflare.com/workers/reference/request-attributes/. If it provided mock values that would mean dev code would not need to account for null.

**Comment by hankjacobs** [comment]
Yeah, totally makes sense. I'll see what we can come up with.

**Comment by jbeeko** [comment]
I don't think it much matters what the values are. This would probably be fine:
```
{
          "tlsVersion" : "TLSv1.3",
          "tlsCipher" : "AEAD-AES128-GCM-SHA256",
          "country" : "US",
          "colo" : "SEA"
}
```

Of course CloudWorker does not run on TLS so you could argue these values are wrong. But short term just having something even if mocked out and wrong is better than null.

**Comment by hankjacobs** [comment]
Yeah I did something close to that. I think I'm OK with it misreporting TLS. I feel the value it provides from a testing perspective out weighs it being incorrect.
