### ISSUE TITLE
TextEncoder doesn't work in Go WebAssembly

### ISSUE THREAD

**Issue by timdp** [dollarshaveclub/cloudworker#64]
With v0.0.10-beta.6, we just ran into an issue that made our Go WASM build throw an obscure `Reflect.get()`-related error. We proceeded to disable the polyfills one by one, and narrowed it down to `text-encoding` crashing.

However, I don't see why the `text-encoding` package is being used in the first place. Node has had its own `TextEncoder` and `TextDecoder` in `util` since version 8.3, and if we use those in our `Context` instead, our WASM code seems to work fine--or at least, it doesn't crash on an internal `Reflect.get()` anymore.

I see `text-encoding` got added in #31. Perhaps Node's internal implementations were never considered as an alternative?

**Comment by hankjacobs** [comment]
Ah interesting. Let me take a look and I’ll get back to you. It should be a simple fix to swap implementations if the node one is suitable.

**Comment by hankjacobs** [comment]
@timdp The most recent beta should do the trick. Let me know if it works for you.
