### ISSUE TITLE
Question about how KV works

### ISSUE THREAD

**Issue by kfatehi** [dollarshaveclub/cloudworker#68]
Hi

I am having trouble understanding how the "TestNamespace" in the example is actually defined?

In other words, when I try to run the example, it throws an error saying it's undefined, but I don't know what to do in order to cause it to be defined.

I'd like to be able to cause it to be defined both from CLI and from Nodejs (because I am using this technique to write unit tests).

I tried using --kv-set, thinking that would cause the namespace to be defined, but it did not cause it to be defined.

Thank you

**Comment by hankjacobs** [comment]
Hi @kfatehi! I've just updated the README to include runnable examples of using `--kv-set` and `--kv-file`. The TestNamespace variable gets defined if there is a `--kv-set` or `--kv-file` flag that has it as the variable portion (e.g. the `variable` part of `--kv-set [variable.key=value]`). `variable` can be anything but it must match what is used within the worker script. For example, `--kv-set TestNamespace.hello=world` will create a TestNamespace variable that conforms to the KV interface as outlined [here](https://developers.cloudflare.com/workers/kv/api/) (scroll down to the section titled "Worker API"), populated with key `hello` with a value of `world`. I'm closing this issue for now but feel free to comment if further clarification is needed. Additionally, feel free to update the README as you see fit and open a PR for those changes.

**Comment by kfatehi** [comment]
Hi @hankjacobs 

Thank you for the quick response. I am now up and running. For future reference, I want to paste some code here in this issue showing how to initialize KV when starting constructing a Cloudworker from JS.

I'm using this in my test harness:

```javascript
const fs = require('fs');
const Cloudworker = require('@dollarshaveclub/cloudworker');
const script = fs.readFileSync('worker.js').toString();
const utils = require('@dollarshaveclub/cloudworker/lib/utils');
const kvset = ['TestNamespace.test=val'];
const kvfile = ['TestNamespace=kv-test.json'];
const bindings = utils.extractKVBindings(kvset, kvfile);
const cw = new Cloudworker(script, { bindings });
```

**Comment by atmin** [comment]
that works, but no need to parse command line params when instrumenting with code:

```js
...
const { KeyValueStore } = require('@dollarshaveclub/cloudworker/lib/kv');
const TestNamespace  = new KeyValueStore('kv-test.json');
// no need for `await`, but in non-test scenario you may want to ack the operation
TestNamespace.put('test', 'val');
const cw = new Cloudworker(script, { TestNamespace });
```
