### ISSUE TITLE
Cannot find module '../build/Release/nodessl.node'

### ISSUE THREAD

**Issue by fabien-h** [dollarshaveclub/cloudworker#72]
I just start the process with `cloudworker dist/server.js` and get this error:

```
internal/modules/cjs/loader.js:615
    throw err;
    ^

Error: Cannot find module '../build/Release/nodessl.node'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:613:15)
    at Function.Module._load (internal/modules/cjs/loader.js:539:25)
    at Module.require (internal/modules/cjs/loader.js:667:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@dollarshaveclub/cloudworker/node_modules/node-webcrypto-ossl/buildjs/native.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:738:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at Module.load (internal/modules/cjs/loader.js:630:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
    at Function.Module._load (internal/modules/cjs/loader.js:562:3)
```

**Comment by hankjacobs** [comment]
Have you tried uninstalling and reinstalling cloudworker? Also, make sure you’re on node v10. If that doesn’t work, what OS are you using?

**Comment by fabien-h** [comment]
Node 11, I installed a couple of times, npm clean in between

**Comment by hankjacobs** [comment]
What OS are you using? I can't repro under Node 11 with my Linux machine.

**Comment by thegeorgeous** [comment]
Happens on macOS Mojave with node v10

**Comment by fabien-h** [comment]
Hi, back on the project. I still have the same issue on macOS Mojave (node 12).

I have this error on build :

`CXX(target)` Release/obj.target/nodessl/src/main.o
Apple LLVM version 10.0.0 (clang-1000.10.44.4)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
 "/Library/Developer/CommandLineTools/usr/bin/clang" -cc1 -triple x86_64-apple-macosx10.7.0 -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -emit-obj -disable-free -disable-llvm-verifier -discard-value-names -main-file-name main.cpp -mrelocation-model pic -pic-level 2 -mthread-model posix -mdisable-fp-elim -fno-strict-return -masm-verbose -munwind-tables -faligned-alloc-unavailable -target-cpu core2 -dwarf-column-info -debug-info-kind=standalone -dwarf-version=2 -debugger-tuning=lldb -target-linker-version 409.12 -v -coverage-notes-file /usr/local/lib/node_modules/@dollarshaveclub/cloudworker/node_modules/node-webcrypto-ossl/build/Release/obj.target/nodessl/src/main.gcno -resource-dir /Library/Developer/CommandLineTools/usr/lib/clang/10.0.0 -dependency-file ./Release/.deps/Release/obj.target/nodessl/src/main.o.d.raw -skip-unused-modulemap-deps -MT Release/obj.target/nodessl/src/main.o -D NODE_GYP_MODULE_NAME=nodessl -D USING_UV_SHARED=1 -D USING_V8_SHARED=1 -D V8_DEPRECATION_WARNINGS=1 -D V8_DEPRECATION_WARNINGS -D V8_IMMINENT_DEPRECATION_WARNINGS -D _DARWIN_USE_64_BIT_INODE=1 -D _LARGEFILE_SOURCE -D _FILE_OFFSET_BITS=64 -D OPENSSL_THREADS -D BUILDING_NODE_EXTENSION -I /Users/fabienhuet/.node-gyp/12.0.0/include/node -I /Users/fabienhuet/.node-gyp/12.0.0/src -I /Users/fabienhuet/.node-gyp/12.0.0/deps/openssl/config -I /Users/fabienhuet/.node-gyp/12.0.0/deps/openssl/openssl/include -I /Users/fabienhuet/.node-gyp/12.0.0/deps/uv/include -I /Users/fabienhuet/.node-gyp/12.0.0/deps/zlib -I /Users/fabienhuet/.node-gyp/12.0.0/deps/v8/include -I ../../nan -stdlib=libc++ -stdlib=libc++ -Os -Wall -Wendif-labels -W -Wno-unused-parameter -std=c++11 -fdeprecated-macro -fdebug-compilation-dir /usr/local/lib/node_modules/@dollarshaveclub/cloudworker/node_modules/node-webcrypto-ossl/build -ferror-limit 19 -fmessage-length 162 -stack-protector 1 -fblocks -fencode-extended-block-signature -fno-rtti -fobjc-runtime=macosx-10.7.0 -fcxx-exceptions -fexceptions -fmax-type-align=16 -fdiagnostics-show-option -fcolor-diagnostics -vectorize-loops -vectorize-slp -o Release/obj.target/nodessl/src/main.o -x c++ ../src/main.cpp
clang -cc1 version 10.0.0 (clang-1000.10.44.4) default target x86_64-apple-darwin17.7.0
ignoring nonexistent directory "/Users/fabienhuet/.node-gyp/12.0.0/src"
ignoring nonexistent directory "/Users/fabienhuet/.node-gyp/12.0.0/deps/openssl/config"
ignoring nonexistent directory "/Users/fabienhuet/.node-gyp/12.0.0/deps/openssl/openssl/include"
ignoring nonexistent directory "/Users/fabienhuet/.node-gyp/12.0.0/deps/uv/include"
ignoring nonexistent directory "/Users/fabienhuet/.node-gyp/12.0.0/deps/zlib"
ignoring nonexistent directory "/Users/fabienhuet/.node-gyp/12.0.0/deps/v8/include"
ignoring nonexistent directory "/usr/include/c++/v1"
#include "..." search starts here:
#include <...> search starts here:
 /Users/fabienhuet/.node-gyp/12.0.0/include/node
 ../../nan
 /Library/Developer/CommandLineTools/usr/include/c++/v1
 /usr/local/include
 /Library/Developer/CommandLineTools/usr/lib/clang/10.0.0/include
 /Library/Developer/CommandLineTools/usr/include
 /usr/include
 /System/Library/Frameworks (framework directory)
 /Library/Frameworks (framework directory)
End of search list.`

**Comment by fabien-h** [comment]
Using yarn solves the issue if someone encounters the same problem.

**Comment by nikhils4** [comment]
The solution to this problem is, if during npm modules installation, the process searches for some directory, let it finish do not interrupt the process. It will complete eventually.
