### ISSUE TITLE
Cannot use webpack Buffer module

### ISSUE THREAD

**Issue by EverlastingBugstopper** [dollarshaveclub/cloudworker#75]
My worker relies on the `Buffer` [package](https://www.npmjs.com/package/buffer) and it works fine in the Cloudflare worker runtime. However when I attempt to use Cloudworker, the method for creating a new Buffer `Buffer.from("Hello, world!")` throws this error: `first argument must be a string or Buffer` (which doesn't really make sense, because the first argument is a string or Buffer)

I tried forking and including the Buffer package directly in the Cloudworker runtime but I had no luck.

**Comment by hankjacobs** [comment]
So this probably has something to do with the way cloudworker is architected. I touched on the underlying issue [in this comment](https://github.com/dollarshaveclub/cloudworker/pull/81#issuecomment-485292676). That being said, I just pushed v0.1.0 that has some improvements in that area so it may work now. Give it a shot and let me know if it's resolved (or not). Closing this issue for now. Thanks!
