### ISSUE TITLE
ReferenceError: URLSearchParams is not defined

### ISSUE THREAD

**Issue by derekargueta** [dollarshaveclub/cloudworker#79]
URLSearchParams is a standard web api - https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams

it'd be great to get a shim for this.

**Comment by larkin-nz** [comment]
Hey @derekargueta

It this working in Cloudflare Workers and not Cloudworker?

**Comment by shalzz** [comment]
Hi, I'm still getting a similar error now with v0.1.1 and nodejs v12:
`TypeError: url_1.URLSearchParams is not a constructor`
