### ISSUE TITLE
Question: How to specify origin/cname for cloudworker

### ISSUE THREAD

**Issue by Goues** [dollarshaveclub/cloudworker#80]
Hello,

we are trying to setup Cloudworke and fail to do this one thing:

Our current setup is `SSL offloading -> Varnish -> Origin` and we are trying replace Varnish with Cloudflare worker. To make caching right, we use a Cloudflare worker to append suffixes based on parameters like this: https://developers.cloudflare.com/workers/recipes/vcl-conversion/delivering-different-content-to-different-devices/.

In cloudflare, this seems to do the right job a sends a modified request to origin. So if `www.example.com` is a CNAME for `my-origin.something.else`, the final request goes to `https://my-origin.something.else/mobile/` with a header `Host: www.example.com`. It is not even needed to change `url.host`, it is automatic, and it just works.

In cloudworker, however, we do not know to provide the CNAME, so the modified request still goes to `https://www.example.com/mobile/` and creates a loop in our setup, because www.example.com is pointing to Cloudworker.

Is there a way to specify CNAME for Cloudworker and/or what the origin is in any meaningful way? So that Cloudworker can listen to `https://www.example.com/`, modify it to `https://www.example.com/mobile/` a pass further to the right origin without having to modfiy `url.host`?

Thank you

**Comment by hankjacobs** [comment]
There's nothing I can think of that would solve this using only cloudworker. Running cloudworker in a container and modifying your machine's `/etc/hosts` file to point `www.example.com` at the container's IP might do the trick.
