### ISSUE TITLE
Production alternative?

### ISSUE THREAD

**Issue by tmikaeld** [dollarshaveclub/cloudworker#93]
If, god forbid, Cloudflare would be unable to operate or be blocked by countries - would it be feasible to run this behind an API Gateway, is it built with security in mind or only for local development testing?

**Comment by hankjacobs** [comment]
It was developed solely with local development in mind and is most definitely not meant to be used in production.

**Comment by tmikaeld** [comment]
Figured as much, I guess it would need to be re-built from the ground up for the use-case.

Makes cloudflare workers quite a lock-in, but I guess that's the point.
