### ISSUE TITLE
Response object does not set url correctly

### ISSUE THREAD

**Issue by tgallacher** [dollarshaveclub/cloudworker#97]
# Summary

First of all, thanks for this package; being able to create unit tests for Cloudflare workers is super helpful!

## Problem
I have a `worker.js` script that includes a call to `Response.redirect()`: 

```js
// worker.js
async function handleRequest(request) {
  return new Promise(resolve => {
     // ... some logic to figure out the `newUrl` value

     return resolve(
       Response.redirect(newUrl, 301)
     );
  });
}
```

With a test:

```js
// cloudworker set up not included in this snippet

new Promise(async (resolve, reject) => {
  const req = new Request(new URL(requestUrl));
  const res = await handleRequest(req);

  try {
    // We don't want to lock in our tests to specific redirects
    // we just want to test that the redirect logic works.
    assert.isAbove(res.status, 300);
    assert.isBelow(res.status, 400);
    assert.include(
      res.url,
      NEW_ORIGIN, // defined above...
      `The origin should change if the redirect part of the migrated pages, req=${requestUrl}`,
    );
  } catch (err) {
    return reject(err);
  }

  return resolve();
}),
```

**Expected Behaviour**

The test passes or fails, depending on the implementation of the `worker.js` code.

**Actual Behaviour**

The test always fails as `res.url` is `undefined`. 

**Info**
@dollarshaveclub/cloudworker: `0.0.11`
@dollarshaveclub/node-fetch: `3.2.0`

## Notes

I've had a look and it looks like the problem comes from the way the `ShimResponse` calls the constructor, and how it matches with the prototype of `Response` constructor of `@dollarshaveclub/node-fetch`.

The `ShimResponse` sets the url in the `Location` header, and the `Response` object (node-fetch) expects it to be supplied as an option. 

See: 

https://github.com/dollarshaveclub/cloudworker/blob/master/lib/runtime/fetch.js#L42

and 

https://github.com/dollarshaveclub/node-fetch/blob/master/src/response.js#L32

If you like, I am happy to raise a PR to resolve this? 

## Workaround

In the meantime, I've got round my testing issue by replacing

```js
    assert.include(
      res.url,
      NEW_ORIGIN, // defined above...
      `The origin should change if the redirect part of the migrated pages, req=${requestUrl}`,
    );
```

with

```js
    assert.include(
      res.headers.get('Location'),,
      NEW_ORIGIN, // defined above...
      `The origin should change if the redirect part of the migrated pages, req=${requestUrl}`,
    );
```

thanks!

**Comment by hankjacobs** [comment]
Hi @tgallacher. From some experimentation, I found that cloudworker's behavior is mostly correct in this scenario when compared against Cloudflare Workers. [Here's an example](https://cloudflareworkers.com/#b0b4b87387ecaf9e8a0b374ca67a4dd9:https://tutorial.cloudflareworkers.com) of how Cloudflare Workers behave. Note in the console that the redirect response URL is empty. I'd be open to a PR fixing cloudworker to match that behavior (empty string instead of undefined) but not for it to be the redirect url. 

All that being said, definitely correct me if I'm misinterpreting this issue. Thanks!
